import csv

vcf_columns = [
"Original Input: Chrom",
"Original Input: Pos",
"Original Input: Reference allele",
"Original Input: Alternate allele",
"Variant Annotation: Gene",
"Variant Annotation: cDNA change",
"Variant Annotation: Protein Change",
"VCF: AF",
"VCF: FAO",
"VCF: FDP",
"VCF: HRUN",
"VCF: Filter",
"VCF: Genotype",
"COSMIC: ID",
"COSMIC: Variant Count",
"COSMIC: Variant Count (Tissue)",
"ClinVar: ClinVar ID",
"ClinVar: Clinical Significance",
"gnomAD3: Global AF",
"PhyloP: Vert Score",
"CADD: Phred",
"PolyPhen-2: HDIV Prediction",
"SIFT: Prediction",
"VCF: FSAF",
"VCF: FSAR",
"VCF: FSRF",
"VCF: FSRR",
"VCF: Fisher Odds Ratio",
"VCF: Fisher P Value",
"VCF: Binom Proportion",
"VCF: Binom P Value",
"Mpileup Qual: Read Depth",
"Mpileup Qual: Start Reads",
"Mpileup Qual: Stop Reads",
"Mpileup Qual: Filtered Reference Forward Read Depth",
"Mpileup Qual: Filtered Reference Reverse Read Depth",
"Mpileup Qual: Unfiltered Reference Forward Read Depth",
"Mpileup Qual: Unfiltered Reference Reverse Read Depth",
"Mpileup Qual: Filtered Variant Forward Read Depth",
"Mpileup Qual: Filtered Variant Reverse Read Depth",
"Mpileup Qual: Filtered Variant Binomial Proportion",
"Mpileup Qual: Filtered Variant Binomial P Value",
"Mpileup Qual: Filtered Variant Fishers Odds Ratio",
"Mpileup Qual: Filtered Variant Fishers P Value",
"Mpileup Qual: Unfiltered Variant Forward Read Depth",
"Mpileup Qual: Unfiltered Variant Reverse Read Depth",
"Mpileup Qual: Unfiltered Variant Binomial Proportion",
"Mpileup Qual: Unfiltered Variant Binomial P Value",
"Mpileup Qual: Unfiltered Variant Fishers Odds Ratio",
"Mpileup Qual: Unfiltered Variant Fishers P Value",
"VCF: LEN",
"VCF: QD",
"VCF: STB",
"VCF: STBP",
"VCF: SVTYPE",
"VCF: TYPE",
"VCF: QUAL",
"Variant Annotation: Coding",
"Variant Annotation: Sequence Ontology",
"Variant Annotation: Transcript",
"Variant Annotation: All Mappings",
"UniProt (GENE): Accession Number",
"dbSNP: rsID",
"MDL: Sample Count",
"MDL: Variant Frequency",
"MDL: Sample List",
]

csv_file = 'VCF_test.csv'
for row in csv.DictReader(csv_file, fieldnames=vcf_columns, delimiter='\t', quotechar="'"):
    row_dict=row
    print(row.keys())
